(6623) add multiple files select
epifanov/cordova-filechooser pull request #1
Opened 2019-07-30 06:01 UTC by retoko

2019-07-30 08:54 UTC, safronovlad requested changes

2019-07-30 08:54 UTC, SafronovVV commented on src/android/FileChooser.java
> +                ClipData clipData = data.getClipData();
Очень много ветвлений, трудно разобрать, можно немножко упростить
```suggestion
public void onActivityResult(int requestCode, int resultCode, Intent data) {
  if (!(requestCode == PICK_FILE_REQUEST && callback != null)) { return; }

  if (resultCode == Activity.RESULT_OK) {
    ClipData clipData = data.getClipData();
    JSONArray savedUris = new JSONArray();
    final int clipDataCount = clipData != null && clipData.getItemCount();

    if (clipDataCount && clipDataCount > 0) {
      for (int i = 0; i < clipDataCount; i++) {
        ClipData.Item item = clipData.getItemAt(i);
        Uri uri = item.getUri();
        if (uri == null) { continue; }

        Log.w(TAG, uri.toString());
        savedUris.put(uri.toString());
      }
    } else {
      Uri uri = data.getData();

      if (uri != null) {
        Log.w(TAG, uri.toString());
        savedUris.put(uri.toString());
      } else {
        callback.error("File uri was null");
      }
    }
    callback.success(savedUris.toString());

  } else if (resultCode == Activity.RESULT_CANCELED) {
    // keep this string the same as in iOS document picker plugin
    // https://github.com/iampossible/Cordova-DocPicker
    callback.error("User canceled.");
  } else {
    callback.error(resultCode);
  }
}
```

2019-07-31 07:45 UTC, safronovlad approved these changes

2019-07-31 11:42 UTC, glee812 approved these changes

2019-08-02 07:08 UTC, merged