(6752) fix attach files
epifanov/cordova-filechooser pull request #2
Opened 2019-08-07 13:21 UTC by retoko

2019-08-08 12:41 UTC, glee812 requested changes

2019-08-08 12:41 UTC, glee812 commented on src/android/FileChooser.java
> +    private void chooseFile(JSONObject filter, CallbackContext callbackContext) {
почему функции стали приватными?

2019-08-08 12:41 UTC, glee812 commented on src/android/FileChooser.java
> -        if (!(requestCode == PICK_FILE_REQUEST && callback != null)) { return; }
зачем развернул это условие?

2019-08-08 14:41 UTC, retoko commented on src/android/FileChooser.java
> +    private void chooseFile(JSONObject filter, CallbackContext callbackContext) {
андроид студия ругается) ну на самом то деле они не должны быть публичными, они используются только внутри класса.

2019-08-09 06:35 UTC, glee812 approved these changes

2019-08-14 11:12 UTC, merged